# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: juan-ser <juan-ser@student.42madrid.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/11 11:48:45 by juan-ser          #+#    #+#              #
#    Updated: 2024/09/11 12:12:16 by juan-ser         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

GCC = gcc
CFLAGS = -Wall -Werror -Wextra -D BUFFER_SIZE=42
INCLUDES = -I.
NAME = libft.a
SRC = 

OBJ = $(SRC:.c=.o)
